In [30]:
import numpy as np
from scipy.stats import multivariate_normal, norm, skewnorm
from scipy.special import owens_t

def sn_cdf2(val, a, mean, var):
    val = (np.array(val) - mean) / np.sqrt(var)
    if a >= 0:
        x = np.array([[v, 0] for v in val])
        roh = -a / np.sqrt(1 + a**2)
        cov = np.array([[1, roh], [roh, 1]])
        return 2 * multivariate_normal.cdf(x, cov=cov)
    else:
        x = np.array([[-v, 0] for v in val])
        roh = a / np.sqrt(1 + a**2)
        cov = np.array([[1, roh], [roh, 1]])
        return 1 - 2 * multivariate_normal.cdf(x, cov=cov)

In [31]:
def sn_cdf1(val, a, mean, var):
    # Todo: add upper / lower tail handling
    val = (np.array(val) - mean) / np.sqrt(var)

    if a >= 0:
        # x = np.array([[v, 0] for v in val])
        # cov = a / np.sqrt(1 + a ** 2)
        # return 2 * multivariate_normal.cdf(x, cov=[[cov, 0], [0, cov]])
        return norm.cdf(val) - 2 * owens_t(val, np.array([a] * len(val)))
    else:
        # x = np.array([[-v, 0] for v in val])
        # cov = - a / np.sqrt(1 + a ** 2)
        # return 1 - 2 * multivariate_normal.cdf(x, cov=[[cov, 0], [0, cov]])
        return 1 - norm.cdf(-val) - 2 * owens_t(-val, np.array([a] * len(val)))


In [57]:
skewnorm.cdf(np.array([0,1,2,3,4,5,5.1,5.2,5.3,5.4,5.5,5.6,5.7,5.8,5.81,5.82,5.83,5.84,5.85], 
                      dtype=np.longdouble), 0.5)

array([0.35241638, 0.75521536, 0.95999971, 0.99743986, 0.99993778,
       0.99999943, 0.99999966, 0.9999998 , 0.99999988, 0.99999993,
       0.99999996, 0.99999998, 0.99999999, 0.99999999, 0.99999999,
       0.99999999, 0.99999999, 0.99999999, 1.        ])

In [58]:
sn_cdf1(np.array([0,1,2,3,4,5,5.1,5.2,5.3,5.4,5.5,5.6,5.7,5.8,5.81,5.82,5.83,5.84,5.85], 
                 dtype=np.longdouble), 0.5, 0, 1)

array([0.35241638, 0.75521536, 0.95999971, 0.99743986, 0.99993778,
       0.99999943, 0.99999966, 0.9999998 , 0.99999988, 0.99999993,
       0.99999996, 0.99999998, 0.99999999, 0.99999999, 0.99999999,
       0.99999999, 0.99999999, 0.99999999, 1.        ])

In [59]:
sn_cdf2(np.array([0,1,2,3,4,5,5.1,5.2,5.3,5.4,5.5,5.6,5.7,5.8,5.81,5.82,5.83,5.84,5.85], 
                 dtype=np.longdouble), 0.5, 0, 1)

array([0.35241638, 0.75521536, 0.95999971, 0.99743986, 0.99993778,
       0.99999943, 0.99999966, 0.9999998 , 0.99999988, 0.99999993,
       0.99999996, 0.99999998, 0.99999999, 0.99999999, 0.99999999,
       0.99999999, 0.99999999, 0.99999999, 1.        ])